baseURL: https://my-new-hugo-si.netlify.app # Replace with your domain
languageCode: en-us
title: "d/dx f8 = saif"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 6
params:
  abbrDateFmt: "Jan 2"
  author: "Blog Author"
  math: true
  dateFmt: "2006-01-02"
  subtitle: "I use arch by the way"

markup:
  goldmark:
    renderer:
      unsafe: true
