baseURL: https://f-8.netlify.app/ # Replace with your domain
languageCode: en-us
title: "d/dx f8 = saif"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about
      weight: 2
    - identifier: portfolio
      name: Resume
      url: /resume/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4
params:
  abbrDateFmt: "Jan 2"
  author: "Blog Author"
  brandIconFile: images/linux-svgrepo-com.svg
  customStylesheets:
    - css/custom.css
  math: true
  dateFmt: "2006-01-02"
  subtitle: "I use arch by the way"

markup:
  goldmark:
    renderer:
      unsafe: true
